### ISSUE TITLE
Start ohne E3DC

### ISSUE THREAD

**Issue by HarrysLapTimer** [nischram/EMD_1#6]
Moin,

auch von mir herzlichen Dank fürs Sharen des E3DC Monitors.

Ich baue gerade ein Gerät für meinen Vater zusammen, soll ein Geschenk werden.
Ich habe die Sketch konfiguriert und übersetzt bekommen.
Nach dem Start erscheint die unten angehängte Anzeige, weiter passiert aber nichts.

Ich bin aktuell natürlich nicht im Netz meines Vaters, ein Zugriff auf den E3DC S10mini ist deshalb nicht möglich.

Ist das wie erwartet, weil keine Daten per MODBUS bezogen werden können?

Ich möchte soviel vorbereiten wie möglich, damit ich dann zum Geburtstag nicht ewig am Rechner sitze. :-)

Danke! 
![IMG_6336](https://user-images.githubusercontent.com/5400797/226171596-f4a8aac4-d368-4429-b43a-69812eb891f7.jpg)

**Comment by HarrysLapTimer** [comment]
Ich habe ein wenig im Code und Log gestöbert, das System wartet auf den MODBUS Antwort und hängt deshalb.

**Comment by nischram** [comment]
Hey,

Grundsätzlich scheint es tatsächlich an dem fehlenden Speicher zu liegen. Aber ich hätte eigentlich erwartet das die Applikation trotzdem startet.

Kannst du eventuell ein Auszug vom "Serieller Monitor" machen und hier hochladen? Dann kann ich mir die Ausgaben ansehen.
Ich habe in der Startfunktion für Modbus zwei Ausgaben siehe Bild in grün:
<img width="500" alt="initModbus" src="https://user-images.githubusercontent.com/19279623/226184611-ee512761-63dd-4114-a9ae-52d963359d64.jpg">

Sollte in der Zeit wo es nicht weiter läuft dauerhaft nur "." dazukommen, da könnte bei der Zeile in rot der Fehler sein. Ich glaube fast die Zeile ist zu viel im Code. Du könntest zum versuch die Zeile mit einer "//" ausblenden. 
Zeile 90 in der Datei "modbus.h" so sieht es geändert aus::
`  //lastMbMillis = millis();`
Danach den Code neu hochladen und testen.

Wenn das klappt läuft die Applikation weiter nach der Zeit die in der "parameter.h" unter "MODBUS_TIMEOUT" eingetragen ist, default bei 4 Sekunden. Die Applikation geht in ein "refresh" Fenster wenn Modbus nicht erreichbar ist. So kann gut per SD-Karte trotzdem ein Update gemacht werden.

Viele Grüße Nico

**Comment by HarrysLapTimer** [comment]
In der Tat, die Punkte kamen wegen des Rücksetzen des Startzeitpunkts in der Schleife dauerhaft. Nach Auskommentieren der Zeile kommt jetzt nach x Sekunden die Meldung, dass der Modbus init erfolglos war und ich lande auf der Seite mit den Neustart-Möglichkeiten. Danke erst mal, am Samstag gehts in die Produktion. PIR und Temperaturesensor sind jetzt auch eingebaut. ;-)

**Comment by nischram** [comment]
Hey,
sehr schön freut mich das es so schnell geklappt hat und so deinem Geschenk nichts im Wege steht (übrigens eine Tolle Idee)!
Ich werde dann in der nächsten Zeit die Version anpassen.
Viele Grüße Nico

**Comment by nischram** [comment]
Update mit V1.08 hochgeladen
