### ISSUE TITLE
Läßt sich leider nicht mit PlatformIO kompilieren

### ISSUE THREAD

**Issue by ats3788** [nischram/EMD_1#8]
Ich bekomme diese Fehler
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (6.5.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20014.231204 (2.0.14) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 46 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Wire @ 2.0.0
|-- SPI @ 2.0.0
|-- FS @ 2.0.0
|-- Time @ 1.6.1
|-- Adafruit GFX Library @ 1.11.9
|-- Adafruit ILI9341 @ 1.6.0
|-- XPT2046_Touchscreen @ 0.0.0-alpha+sha.26b691b2c8
|-- OpenWeatherOneCall @ 3.3.1
|-- modbus-esp8266 @ 4.1.0
|-- SPIFFS @ 2.0.0
|-- Update @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- Preferences @ 2.0.0
|-- WiFi @ 2.0.0
|-- SD @ 2.0.0
|-- ArduinoOTA @ 2.0.0
Building in release mode
Compiling .pio\build\esp32dev\src\main.cpp.o
Archiving .pio\build\esp32dev\libc31\libFS.a
Indexing .pio\build\esp32dev\libc31\libFS.a
Archiving .pio\build\esp32dev\lib875\libTime.a
Indexing .pio\build\esp32dev\lib875\libTime.a
In file included from src/main.cpp:10:
src/parameter.h:7: warning: "ESP32" redefined
 #define ESP32

<command-line>: note: this is the location of the previous definition
Compiling .pio\build\esp32dev\lib1ec\Adafruit BusIO\Adafruit_BusIO_Register.cpp.o
Compiling .pio\build\esp32dev\lib1ec\Adafruit BusIO\Adafruit_I2CDevice.cpp.o
Compiling .pio\build\esp32dev\lib1ec\Adafruit BusIO\Adafruit_SPIDevice.cpp.o
In file included from src/weatherGui.h:23,
                 from src/main.cpp:31:
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:304:5: warning: 'typedef' was ignored in this declaration
     typedef union FLAGS
     ^~~~~~~
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:88:30: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
         char CITY[60] = {NULL};
                              ^
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:89:31: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
         char STATE[10] = {NULL};
                               ^
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:90:33: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
         char COUNTRY[10] = {NULL};
                                 ^
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:288:44: warning: converting to non-pointer type 'char' from NULL [-Wconversion-null]
         char OPEN_WEATHER_DKEY[100] = {NULL};
                                            ^
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:291:39: warning: converting to non-pointer type 'float' from NULL [-Wconversion-null]
         float OPEN_WEATHER_LATITUDE = NULL;
                                       ^~~~
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:292:40: warning: converting to non-pointer type 'float' from NULL [-Wconversion-null]
         float OPEN_WEATHER_LONGITUDE = NULL;
                                        ^~~~
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:294:37: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
         int OPEN_WEATHER_EXCLUDES = NULL;
                                     ^~~~
.pio/libdeps/esp32dev/OpenWeatherOneCall/src/OpenWeatherOneCall.h:295:36: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
         int OPEN_WEATHER_HISTORY = NULL;
                                    ^~~~
In file included from src/main.cpp:31:
src/weatherGui.h:95:17: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
 int myHISTORY = NULL;            //<-----Only required for historical data up to 5 days
                 ^~~~
src/weatherGui.h: In function 'void startWeatherCall()':
src/weatherGui.h:114:39: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
     OWOC.setOpenWeatherKey(WEATHER_KEY);
                                       ^
src/main.cpp: In function 'void loop()':
src/main.cpp:145:125: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
           overwriteLcdTextWorth(6, 93, 82, 12, ILI9341_DARKGREY, ILI9341_WHITE, FontMonospaced_bold_16,"W", "%6d",solarPower);
                                                                                                                             ^
src/main.cpp:146:126: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
           overwriteLcdTextWorth(148, 93, 82, 12, ILI9341_DARKGREY, ILI9341_WHITE, FontMonospaced_bold_16,"W", "%6d",gridPower);
                                                                                                                              ^
src/main.cpp:147:124: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
           overwriteLcdTextWorth(6, 284, 82, 12, ILI9341_DARKGREY, ILI9341_WHITE, FontMonospaced_bold_16,"W", "%6d",batPower);
                                                                                                                            ^
src/main.cpp:148:127: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
           overwriteLcdTextWorth(148, 284, 82, 12, ILI9341_DARKGREY, ILI9341_WHITE, FontMonospaced_bold_16,"W", "%6d",homePower);
                                                                                                                               ^
src/main.cpp:390:41: error: 'findUpdate' was not declared in this scope
           if (touchField(Main_R2_S1) && findUpdate != 0) {
                                         ^~~~~~~~~~
src/main.cpp:390:41: note: suggested alternative: 'menuUpdate'
           if (touchField(Main_R2_S1) && findUpdate != 0) {
                                         ^~~~~~~~~~
                                         menuUpdate
src/main.cpp:394:26: error: 'SD_MMC' was not declared in this scope
             updateFromFS(SD_MMC, updateFile);
                          ^~~~~~
src/main.cpp:394:26: note: suggested alternative: 'CARD_MMC'
             updateFromFS(SD_MMC, updateFile);
                          ^~~~~~
                          CARD_MMC
src/main.cpp:394:34: error: 'updateFile' was not declared in this scope
             updateFromFS(SD_MMC, updateFile);
                                  ^~~~~~~~~~
src/main.cpp:394:34: note: suggested alternative: 'Update'
             updateFromFS(SD_MMC, updateFile);
                                  ^~~~~~~~~~
                                  Update
src/main.cpp:394:13: error: 'updateFromFS' was not declared in this scope
             updateFromFS(SD_MMC, updateFile);
             ^~~~~~~~~~~~
src/main.cpp:402:16: error: 'checkSdCard' was not declared in this scope
           if (!checkSdCard()){
                ^~~~~~~~~~~
src/main.cpp:408:28: error: 'updateFile' was not declared in this scope
             checkUpdateBin(updateFile);
                            ^~~~~~~~~~
src/main.cpp:408:28: note: suggested alternative: 'Update'
             checkUpdateBin(updateFile);
                            ^~~~~~~~~~
                            Update
src/main.cpp:408:13: error: 'checkUpdateBin' was not declared in this scope
             checkUpdateBin(updateFile);
             ^~~~~~~~~~~~~~
src/main.cpp:408:13: note: suggested alternative: 'menuUpdate'
             checkUpdateBin(updateFile);
             ^~~~~~~~~~~~~~
             menuUpdate
src/main.cpp:409:17: error: 'findUpdate' was not declared in this scope
             if (findUpdate != 0){
                 ^~~~~~~~~~
src/main.cpp:409:17: note: suggested alternative: 'menuUpdate'
             if (findUpdate != 0){
                 ^~~~~~~~~~
                 menuUpdate
src/main.cpp:413:123: error: 'updateInfo1' was not declared in this scope
               printLcdText(touchXmin[Small_R2_S2]+8, touchYmin[Small_R2_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo1);
                                                                                                                           ^~~~~~~~~~~
src/main.cpp:428:15: error: 'returnUpdate' was not declared in this scope
           if (returnUpdate == 1){
               ^~~~~~~~~~~~
src/main.cpp:428:15: note: suggested alternative: 'afterUpdate'
           if (returnUpdate == 1){
               ^~~~~~~~~~~~
               afterUpdate
src/main.cpp:431:121: error: 'updateInfo1' was not declared in this scope
             printLcdText(touchXmin[Small_R2_S2]+8, touchYmin[Small_R2_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo1);
                                                                                                                         ^~~~~~~~~~~
src/main.cpp:433:121: error: 'updateInfo2' was not declared in this scope
             printLcdText(touchXmin[Small_R3_S2]+8, touchYmin[Small_R3_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo2);
                                                                                                                         ^~~~~~~~~~~
src/main.cpp:442:121: error: 'updateInfo1' was not declared in this scope
             printLcdText(touchXmin[Small_R2_S2]+8, touchYmin[Small_R2_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo1);
                                                                                                                         ^~~~~~~~~~~
src/main.cpp:444:121: error: 'updateInfo2' was not declared in this scope
             printLcdText(touchXmin[Small_R3_S2]+8, touchYmin[Small_R3_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo2);
                                                                                                                         ^~~~~~~~~~~
src/main.cpp:449:121: error: 'updateInfo1' was not declared in this scope
             printLcdText(touchXmin[Small_R2_S2]+8, touchYmin[Small_R2_S2]+25, ILI9341_DARKGREY, FontSansSerif_plain_11, updateInfo1);
                                                                                                                         ^~~~~~~~~~~
Compiling .pio\build\esp32dev\libc68\Adafruit GFX Library\Adafruit_GFX.cpp.o
*** [.pio\build\esp32dev\src\main.cpp.o] Error 1

**Comment by nischram** [comment]
Hallo,

ich habe meine Software ausschließlich mit ArduinoIDE programmiert und getestet. Ich nutze PlattformIO nicht und kann somit keine Unterstützung leisten.

Viele Grüße Nico
